spring:
  application:
    name: ledgevent

  security:
    jwt:
      expirationMs: 900000
      jwtSecretKey: PtQo0XZurgs0vQCF39/BIcEICPg4BZnv6EqlbJnDKZ4=

  data:
    redis:
      host: localhost
      port: 6379
